### ISSUE TITLE
Shiny on your github site

### ISSUE THREAD

**Issue by glennmschultz** [toddwschneider/shiny-salesman#2]
Hi Todd, cool loan level analysis but what I really want to know is how did you get shiny to run on github?

**Comment by vnijs** [comment]
What you see on the landing page for this repo is an animated gif. Is that what you were referring to @glennmschultz @toddwschneider  What tool(s) did you use to make the gif?

**Comment by glennmschultz** [comment]
Oh that how I thought you had shiny working on fit

**Comment by toddwschneider** [comment]
@glennmschultz @vnijs correct, the animation in the readme is an animated gif, not a hosted shiny app. I used the `saveGIF()` function from the `animation` package to generate it: http://www.inside-r.org/packages/cran/animation/docs/saveGIF

The actual app is [hosted at shinyapps.io](https://gallery.shinyapps.io/shiny-salesman/) and embedded [on my site](http://toddwschneider.com/posts/traveling-salesman-with-simulated-annealing-r-and-shiny/#salesman-app) via an iframe
