### ISSUE TITLE
Dataset info

### ISSUE THREAD

**Issue by guillaume-chevalier** [toddwschneider/shiny-salesman#3]
Hi, 

Is this an existing dataset or data that you created? If it was already existing, would you have the link for its description or something?

Thanks.

**Comment by toddwschneider** [comment]
Hi, the cities data came from the `us.cities` and `world.cities` datasets that are part of the `maps` package

See pages 31 and 34 of the documentation here: https://cran.r-project.org/web/packages/maps/maps.pdf
